"""Make conflict facts nullable for anomalies

Revision ID: 5e5ee6040456
Revises: f5141b7fc326
Create Date: 2026-08-09 19:44:19.698652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5ee6040456'
down_revision: Union[str, Sequence[str], None] = 'f5141b7fc326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conflicts', 'fact_a_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conflicts', 'fact_b_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conflicts', 'fact_b_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conflicts', 'fact_a_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
