"""Initial schema setup

Revision ID: f5141b7fc326
Revises: 
Create Date: 2026-08-09 04:06:25.571390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5141b7fc326'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLASSIFYING', 'EXTRACTING', 'PAUSED_FOR_REVIEW', 'COMPLETED', 'FAILED', name='runstatus'), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Float(), nullable=True),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'CLASSIFIED', 'EMBEDDED', 'PROCESSED', 'FAILED', 'IGNORED_DUPLICATE', name='documentstatus'), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_run_id'), 'documents', ['run_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('event_details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_index(op.f('ix_event_logs_node_name'), 'event_logs', ['node_name'], unique=False)
    op.create_index(op.f('ix_event_logs_run_id'), 'event_logs', ['run_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('proposed_action', sa.Text(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'EDITED', name='reviewdecision'), nullable=True),
    sa.Column('human_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_id'), 'review_items', ['id'], unique=False)
    op.create_index(op.f('ix_review_items_item_type'), 'review_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_review_items_run_id'), 'review_items', ['run_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('page_number', sa.String(), nullable=True),
    sa.Column('paragraph_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_document_id'), 'facts', ['document_id'], unique=False)
    op.create_index(op.f('ix_facts_id'), 'facts', ['id'], unique=False)
    op.create_index(op.f('ix_facts_key'), 'facts', ['key'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('fact_a_id', sa.String(), nullable=False),
    sa.Column('fact_b_id', sa.String(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'RESOLVED_KEPT_A', 'RESOLVED_KEPT_B', 'RESOLVED_MANUAL_EDIT', name='conflictstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fact_a_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['fact_b_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_id'), 'conflicts', ['id'], unique=False)
    op.create_index(op.f('ix_conflicts_run_id'), 'conflicts', ['run_id'], unique=False)
    op.create_index(op.f('ix_conflicts_status'), 'conflicts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflicts_status'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_run_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_facts_key'), table_name='facts')
    op.drop_index(op.f('ix_facts_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_document_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_review_items_run_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_item_type'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_event_logs_run_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_node_name'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_run_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
